ALTER TABLE `user`
  ADD COLUMN `nickname` VARCHAR(50) NULL AFTER `name`,
  ADD COLUMN `password` VARCHAR(255) NULL AFTER `nickname`,
  MODIFY COLUMN `gender` VARCHAR(15) NULL,
  MODIFY COLUMN `birth` DATE NULL,
  MODIFY COLUMN `address` VARCHAR(255) NULL,
  MODIFY COLUMN `phone_number` VARCHAR(15) NULL;
